name: Java CI

on: 
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set up Maven cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build with Maven
      run: |
        mvn --batch-mode clean verify

    - name: Configure Google Cloud account
      run: |
        gcloud config set project tunebrowser
        echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -f src/main/docker/Dockerfile.jvm -t eu.gcr.io/tunebrowser/matt .
        docker push eu.gcr.io/tunebrowser/matt
        